1번: 로또번호를 추출하는 함수를 만들어 보세요!

로또번호는 1번부터 45번까지 복원추출 하지 않고 무작위 6개의 숫자로 이루어집니다!

In [1]:
#1 Solution
import numpy as np
def generate_lottery_numbers():
    return np.random.choice(np.arange(1,46), size=6, replace=False)


2번: 몬테카를로 기법을 활용하여 원주율 구하기

* 몬테카를로 기법: 무수히 많은 무작위 난수를 추출하여 원하는 값을 추정하는 방식
* 전체 시도 횟수 = 10,000,000 번으로 고정
* 아래 그림 참고   

![montecarlo_pi](./montecarlo_pi.gif)

In [ ]:
#2 Solution

#비례식 세우기!
# pi / 4 : 1 = 원 안에 들어간 횟수 : 전체 시도 횟수
# pi = 4*(원 안에 들어간 횟수)/전체 시도 횟수
import numpy as np
total = int(1e7)
sample = np.random.rand(total,2)
pi = np.sum(np.sum(sample**2,axis=1)<=1)/total*4
pi

3 Convert a 1D array to 2D array with 2 rows

For instance,

Input: \[0,1,2,3,4,5,6,7,8,9]

Desired Output:

(\[\[0,1,2,3,4\],

  \[5,6,7,8,9\]\])

In [ ]:
#3 Solution
arr = np.arange(10)
arr.reshape(2,-1)  #Setting to -1 autumatically decides the number of columns

4. 두 개의 np.array에서 공통된 것들을 추출하는 함수를 만드세요.

Input

a = np.array(\[1,2,3,2,3,4,3,4,5,6\])

b = np.array(\[7,2,10,2,7,4,9,4,9,8\])

Desired Output = (\[2,4\])

In [ ]:
#4 Solution - 1
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

In [8]:
#4 Solution - 2
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= np.unique(np.array([x for x in a if x in b]))
c


array([2, 4])

#5 모든 값이 True인 3*3 numpy array를 만들어보세요

In [9]:
#5-1 Solution
np.full((3,3),True,dtype=bool)

#5-2 Solution
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#6 주어진 array에서 짝수, 또는 홀수만 추출하세요

Input = (\[0,1,2,3,4,5,6,7,8,9\])

In [ ]:
#6 Solution
arr = np.array([0,1,2,3,4,5,6,7,8,9])
Odd_number = arr[arr%2==1]

#7 모든 홀수를 -1로 바꾸세요.

Input = (\[0,1,2,3,4,5,6,7,8,9\])

In [10]:
#7 Solution
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2 == 1] = -1

#8 주어진 array에서 5와 10 사이의 모든 수를 추출하세요  
a = np.array(\[2,6,1,9,10,3,27\])

In [17]:
#8 Solution
#1)
a[(a>=5) & (a<=10)]

#2)
index = np.where((a>=5)&(a<=10))
a[index]


array([ 6,  9, 10])

#9 주어진 array의 숫자들의 순위로 이루어진 array를 출력하세요.

Hint:argsort()를 활용하세요.

argsort()는 작은 값부터 순서대로 데이터의 index를 반환해줍니다.

In [18]:
#9
np.random.seed(10)
a = np.random.randint(20,size=10)
#print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [20]:
#9 Solution
print(a.argsort())
print(a.argsort().argsort())

[3 9 1 7 0 8 2 5 4 6]
[4 2 6 0 8 7 9 3 5 1]
