# 1. 로또번호를 추출하는 함수를 만들어 보세요!

로또번호는 1번부터 45번까지 복원추출 하지 않고 무작위 6개의 숫자로 이루어집니다!

In [1]:
# 과제 1 해답
import numpy as np
print(np.random.choice(46, 6,replace=False
))

[26 20  8 18 44 23]


# 2. 몬테카를로 기법을 활용하여 원주율 구하기

* 몬테카를로 기법: 무수히 많은 무작위 난수를 추출하여 원하는 값을 추정하는 방식
* 전체 시도 횟수 = 10,000,000 번으로 고정
* 아래 그림 참고   

In [3]:
from IPython.display import Image


# 참고 이미지
Image("./img/montecarlo_pi.gif")

FileNotFoundError: No such file or directory: &#39;./img/montecarlo_pi.gif&#39;

In [4]:
# 과제 2 해답
x = np.random.random_sample((1, 10000000))
y = np.random.random_sample((1, 10000000))
a=x**2 + y**2
print(4*len(a[a<1])/10000000)


3.1413156


# 3. Convert a 1D array to 2D array with 2 rows

For instance,

Input: \[0,1,2,3,4,5,6,7,8,9]

Desired Output:

(\[\[0,1,2,3,4\],

  \[5,6,7,8,9\]\])

In [5]:
# 과제 3 해답
# a = 스페이스바로 이어서 입력함(1 2 3 4 5 6 이렇게).... 2열    로 맞추는 거니까 홀수면 에러 나는게 정상인가요?
a = list(map(int,input().split()))
Input = np.array(a)
array = Input.reshape(2,-1)
print(array)

[[1 2 3]
 [4 5 6]]


# 4. 두 개의 np.array에서 공통된 것들을 추출하는 함수를 만드세요.

Input

a = np.array(\[1,2,3,2,3,4,3,4,5,6\])

b = np.array(\[7,2,10,2,7,4,9,4,9,8\])

Desired Output = (\[2,4\])

In [49]:
# 과제 4 해답
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(list(set(a[a==b])))

[2, 4]


# 5. 모든 값이 True인 3*3 numpy array를 만들어보세요

In [61]:
# 과제 5 해답
a = np.zeros((3, 3))
print(a==0)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 6. 주어진 array에서 짝수, 또는 홀수만 추출하세요

Input = (\[0,1,2,3,4,5,6,7,8,9\])

In [114]:
# 과제 6 해답
Input = np.array([0,1,2,3,4,5,6,7,8,9])
print(Input[Input%2==1])

[1 3 5 7 9]


# 7. 모든 홀수를 -1로 바꾸세요.

Input = (\[0,1,2,3,4,5,6,7,8,9\])

In [140]:
# 과제 7 해답
Input = np.array([0,1,2,3,4,5,6,7,8,9])
Input[Input % 2==1]=-1
print(Input)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# 8. 주어진 array에서 5와 10 사이의 모든 수를 추출하세요  
a = np.array(\[2,6,1,9,10,3,27\])

In [128]:
# 과제 8 해답
a = np.array([2,6,1,9,10,3,27])
print(a[(a>=5)&(a<=10)])

[ 6  9 10]


# 9. 주어진 array의 숫자들의 순위로 이루어진 array를 출력하세요.

Hint:argsort()를 활용하세요.

argsort()는 작은 값부터 순서대로 데이터의 index를 반환해줍니다.

In [6]:
# 과제 9 해답
# a = 스페이스바로 이어서 입력함(1 2 3 4 5 6 이렇게)
a = list(map(int,input().split()))
b=np.array(a)
print(np.argsort(b)+1)

[4 3 1 2 5]
