In [2]:
#문제 1
import random

lucky=random.sample(range(1, 46), 6)
print(lucky)


[6, 25, 40, 23, 1, 38]


In [3]:
#문제 2
import random

n=10000000
count=0
for i in range(n):
  x=random.uniform(0, 1.0)
  y=random.uniform(0, 1.0)
  if(x**2+y**2<=1):
    count=count+1
print(a)

NameError: name &#39;a&#39; is not defined

In [45]:
#문제 3
import numpy as np

arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2h=np.reshape(arr, (2, 5))
print(arr2h)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [70]:
#문제 4
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
result = list(set(a) & set(b))

print(result)


[2, 4]


In [7]:
#문제 5
import numpy as np
a = np.zeros((3, 3))
print(a==0)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [68]:
#문제 6
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = []
for i in a:
    if i % 2 == 0:
        b.append(i)
    
print(b)

c = []
for j in a:
    if j % 2 != 0:
        c.append(j)

print(c)

[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]


In [56]:
#문제 7
import numpy as np
    
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
j = np.where(a%2 != 0, -1, a)

print(j)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [65]:
#문제 8
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
def five_ten(a):
    return 5 <= a <= 10

newlist = list(filter(five_ten, a)) 
print (newlist)


[6, 9, 10]


In [51]:
#문제 9
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
j = a.argsort()

print(a[j])

[ 1  2  3  6  9 10 27]
